# Expanded Keywords & Phrases for injury detection
INJURY_KEYWORDS = [
    # Specific Conditions
    "torn acl",
    "torn mcl",
    "torn lcl",
    "torn pcl",
    "torn achilles",
    "torn meniscus",
    "high ankle sprain",
    "concussion protocol",
    "sports hernia",
    "tommy john surgery",
    "lisfranc injury",
    "turf toe",
    "plantar fasciitis",
    "broken bone",
    "fractured rib",
    "acl",
    "mcl",
    "lcl",
    "pcl",
    "meniscus",
    # General Terms
    "knee",
    "shoulder",
    "ankle",
    "hamstring",
    "concussion",
    "foot",
    "groin",
    "hip",
    "back",
    "neck",
    "elbow",
    "calf",
    "quadriceps",
    "pectoral",
    "achilles",
    "thumb",
    "fibula",
    "finger",
    "hand",
    "wrist",
    "ribs",
    "chest",
    "biceps",
    "triceps",
    "oblique",
    "abdomen",
    "quad",
    "hammy",
    "toe",
    "shin",
    "forearm",
    # Descriptors (often part of a phrase)
    "strain",
    "sprain",
    "tear",
    "fracture",
    "break",
    "bruise",
    "contusion",
    "soreness",
    "tightness",
    "inflammation",
    "dislocation",
    "surgery",
    "undisclosed",
    "lower body",
    "upper body",
    "lower-body",
    "upper-body",
    "orbital fracture",
]

STATUS_KEYWORDS = [
    "IR",
    "injured reserve",
    "doubtful",
    "questionable",
    "out",
    "ruled out",
    "DNP",
    "limited",
    "full",
    "probable",
    "active",
    "inactive",
    "carted off",
    "week-to-week",
    "will miss",
    "good to go",
    "day-to-day",
    "remainder of the season",
    "rest of the season",
    "season ending",
    "season-ending",
    "out for the season",
    "out for the year",
    "miss the season",
    "reverted",
    "added to ir",
    "added to injured reserve",
    "placed on ir",
    "placed on injured reserve",
    "removed from ir",
    "removed from injured reserve",
    "activated from ir",
    "activated from injured reserve",
    "designated to return",
    "listed as questionable",
    "listed as doubtful",
    "listed as limited",
    "listed as out",
    "full participant",
    "sat out"
]

ORG_BLACKLIST = [
    "NFL Network",
    "NFL",
    "ESPN",
]